import type { DeerSchema } from "@/data/DeerSchema";
import { Input } from "./ui/input";
import React from "react";
import assets from "../../public/assets-manifest.json";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "./ui/dialog";
import { Button } from "./ui/button";
import { ArrowLeft, File, Folder } from "lucide-react";
import { Field, FieldLabel } from "./ui/field";

type AssetEntry =
  | { path: string; type: "directory"; entries: AssetEntry[] }
  | { path: string; type: "file"; license: string | null };

const normalizeAssetPath = (assetPath: string) => `/${assetPath.replace(/^\/+/, "")}`;

const getParentPath = (assetPath: string) => {
  const segments = normalizeAssetPath(assetPath).split("/").filter(Boolean);
  return segments.length > 1 ? `/${segments.slice(0, -1).join("/")}` : "/";
};

const getAssetName = (assetPath: string) => assetPath.split("/").filter(Boolean).at(-1) ?? "/";

export function AssetsTab({
  deerSchema,
  updateDeerSchema,
}: {
  deerSchema: DeerSchema;
  updateDeerSchema: (updatedSchema: DeerSchema) => void;
}) {
  const [path, setPath] = React.useState<string>("/character/blue_knight/blue_knight.png");

  return (
    <div className="flex flex-col gap-0">
      <h1>Bilder und Dateien</h1>
      <BundledAssetSelector path={path} setPath={setPath} />
    </div>
  );
}

export function BundledAssetSelector({
  path,
  setPath,
  extensions = null,
}: {
  path: string;
  setPath: (newPath: string) => void;
  extensions?: string[] | null;
}) {
  const normalizedPath = normalizeAssetPath(path);
  const [selectedFolder, setSelectedFolder] = React.useState(getParentPath(normalizedPath));
  const [selectedPath, setSelectedPath] = React.useState(normalizedPath);
  const [open, setOpen] = React.useState(false);

  // "assets" is a json file with the structure of the assets folder, generated by the assetManifest plugin
  const assetsManifest = assets as AssetEntry[];

  const getEntriesInFolder = (folderPath: string) => {
    if (folderPath === "/") return assetsManifest;
    const folder = findFolderInManifest(assetsManifest, folderPath);
    if (!folder || folder.type !== "directory") return [];
    return folder.entries.filter((entry) => {
      if (entry.type === "directory") return true;
      const ext = getFileExtension(entry.path);
      return extensions ? extensions.includes(ext) : true;
    });
  };

  const findFolderInManifest = (
    manifest: AssetEntry[] | AssetEntry,
    folderPath: string,
  ): AssetEntry | null => {
    if (Array.isArray(manifest)) {
      for (const entry of manifest) {
        const found = findFolderInManifest(entry, folderPath);
        if (found) return found;
      }
      return null;
    }

    if (normalizeAssetPath(manifest.path) === folderPath) return manifest;
    if (manifest.type !== "directory") return null;
    for (const entry of manifest.entries) {
      if (entry.type === "directory") {
        const found = findFolderInManifest(entry, folderPath);
        if (found) return found;
      }
    }
    return null;
  };

  const getFileExtension = (filePath: string) => {
    return filePath.split(".").pop()?.toLowerCase() ?? "";
  };

  const entriesInSelectedFolder = selectedFolder ? getEntriesInFolder(selectedFolder) : [];
  const showBackOneLevel = selectedFolder !== "/";

  const handleOpenChange = (nextOpen: boolean) => {
    setOpen(nextOpen);
    if (nextOpen) {
      const currentPath = normalizeAssetPath(path);
      setSelectedPath(currentPath);
      setSelectedFolder(getParentPath(currentPath));
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger render={<Button variant="outline" />}>Select Asset</DialogTrigger>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Select bundled asset</DialogTitle>
          <DialogDescription>Browse the bundled files and choose an asset.</DialogDescription>
        </DialogHeader>
        <div className="max-h-[55vh] min-h-64 overflow-y-auto rounded-lg border border-[var(--border-color)] bg-muted/30 p-3">
          <div className="grid grid-cols-3 gap-3 sm:grid-cols-5">
            {showBackOneLevel && (
              <AssetTile label="Back" onClick={() => setSelectedFolder(getParentPath(selectedFolder))}>
                <ArrowLeft className="size-8" />
              </AssetTile>
            )}
            {entriesInSelectedFolder.map((entry) => {
              const entryPath = normalizeAssetPath(entry.path);
              return (
                <AssetTile
                  key={entryPath}
                  label={getAssetName(entryPath)}
                  selected={entry.type === "file" && selectedPath === entryPath}
                  onClick={() =>
                    entry.type === "directory" ? setSelectedFolder(entryPath) : setSelectedPath(entryPath)
                  }
                >
                  {entry.type === "directory" ? (
                    <Folder className="size-14 fill-current text-primary/70" size="lg" />
                  ) : getFileExtension(entryPath) === "png" ? (
                    <img
                      src={`/bundled-assets${entryPath}`}
                      alt=""
                      className="size-12 object-contain [image-rendering:pixelated]"
                    />
                  ) : (
                    <File className="size-9 text-muted-foreground" />
                  )}
                </AssetTile>
              );
            })}
          </div>
          {entriesInSelectedFolder.length === 0 && !showBackOneLevel && (
            <p className="py-16 text-center text-muted-foreground">No entries found in this folder.</p>
          )}
        </div>
        <Field>
          <FieldLabel>Selected Asset Path</FieldLabel>
          <Input value={selectedPath} readOnly />
        </Field>
        <DialogFooter>
          <DialogClose render={<Button variant="outline" />}>Cancel</DialogClose>
          <Button
            onClick={() => {
              setPath(selectedPath);
              setOpen(false);
            }}
          >
            Select
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function AssetTile({
  children,
  label,
  selected = false,
  onClick,
}: {
  children: React.ReactNode;
  label: string;
  selected?: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      aria-pressed={selected || undefined}
      title={label}
      onClick={onClick}
      className={`flex aspect-square min-w-0 flex-col items-center justify-center gap-2 rounded-lg border p-2 text-xs transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${
        selected
          ? "border-primary bg-primary/10 text-primary ring-2 ring-primary/30"
          : "border-border bg-background hover:border-primary/50 hover:bg-accent"
      }`}
    >
      {children}
      <span className="w-full truncate text-center">{label}</span>
    </button>
  );
}
