version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
  - package-ecosystem: "docker"
    directory: "/tracking/backend"
    schedule:
      interval: "weekly"
    labels: []
  - package-ecosystem: "docker-compose"
    directory: "/tracking"
    schedule:
      interval: "weekly"
    labels: []
