version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
  - package-ecosystem: "npm"
    directory: "/blockly/frontend"
    schedule:
      interval: "weekly"
    labels: []
