import blockly.dgir.compiler.java.java.JavaCompiler;

import blockly.dgir.compiler.JavaCompiler;
import core.utils.logging.DungeonLogger;
import server.Server;

import java.util.Optional;

import static dgir.dialect.builtin.BuiltinOps.ProgramOp;

/**
 * This class is used to run Java code generated by the Blockly language. It compiles the code
 * dynamically.
 *
 * <p>It uses the Java Compiler API to compile the code and then uses reflection to execute it. The
 * code is executed in a separate thread to avoid blocking the main thread. The class also provides
 * methods to check if the code is currently running and to stop the execution of the code.
 *
 * <p>This class is a singleton, meaning that there is only one instance of it in the application.
 *
 * @see Server Server
 */
public class BlocklyCodeRunner {

  private static final DungeonLogger LOGGER = DungeonLogger.getLogger(BlocklyCodeRunner.class);
  private static BlocklyCodeRunner instance;

  private static final String baseCode =
"""
import Dungeon.Hero;

public class Main {
  %s
}
""";

  private BlocklyCodeRunner() {} // private constructor for singleton

  /**
   * Returns the instance of the BlocklyCodeRunner.
   *
   * @return The instance of the BlocklyCodeRunner.
   */
  public static BlocklyCodeRunner instance() {
    if (instance == null) {
      instance = new BlocklyCodeRunner();
    }
    return instance;
  }

  public boolean isRunning() {
    return false;
  }

  public void stopExecution() {}

  public void compileAndRunCode(String code) {
    compileAndRunCode(code, 0);
  }

  public void compileAndRunCode(String code, int sleepAfterEachLine) {
    String completeCode = String.format(baseCode, code);
    LOGGER.info("Compiling and running code: " + completeCode);
    Optional<ProgramOp> program = JavaCompiler.compileSource(completeCode, "Main.java");
    if (program.isEmpty()) {
      LOGGER.error("Failed to compile code");
      return;
    }
  }
}
