package dsl.semanticanalysis.typesystem.typebuilding.type;

import dsl.semanticanalysis.scope.IScope;
import dsl.semanticanalysis.symbol.ScopedSymbol;
import dsl.semanticanalysis.typesystem.typebuilding.TypeBuilder;
import java.lang.reflect.Field;
import java.util.HashMap;

/** AggregateType. */
public class AggregateType extends ScopedSymbol implements IType {
  /** The name symbol name. */
  public static String NAME_SYMBOL_NAME = "$NAME$";

  protected Class<?> originType;
  private HashMap<String, Field> typeMemberToField;

  /**
   * Constructor.
   *
   * @param name Name of this type
   * @param parentScope parent scope of this type
   */
  public AggregateType(String name, IScope parentScope) {
    super(name, parentScope, null);
    originType = null;
    typeMemberToField = new HashMap<>();
  }

  /**
   * Constructor.
   *
   * @param name Name of this type
   * @param parentScope parent scope of this type
   * @param originType the origin java class of this {@link AggregateType}, if it was generated by
   *     the {@link TypeBuilder}
   */
  public AggregateType(String name, IScope parentScope, Class<?> originType) {
    super(name, parentScope, null);
    this.originType = originType;
    typeMemberToField = new HashMap<>();
  }

  /**
   * Sets the type member to field mapping.
   *
   * @param typeMemberToField the type member to field mapping
   */
  public void setTypeMemberToField(HashMap<String, Field> typeMemberToField) {
    this.typeMemberToField = typeMemberToField;
  }

  /**
   * Gets the type member to field mapping.
   *
   * @return the type member to field mapping
   */
  public HashMap<String, Field> getTypeMemberToField() {
    return this.typeMemberToField;
  }

  @Override
  public Kind getTypeKind() {
    return Kind.Aggregate;
  }

  /**
   * @return the origin java class (or null, if it was not set)
   */
  public Class<?> getOriginType() {
    return this.originType;
  }
}
