name: Java CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
    spotless-server:
        name: Spotless Server
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Spotless
                working-directory: ./lsp-server
                run: ./gradlew spotlessJavaCheck

    checkstyle-server:
        name: Checkstyle Server
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Checkstyle
                working-directory: ./lsp-server
                run: ./gradlew checkstyleMain checkstyleTest
                
    spotless-intellij-plugin:
        name: Spotless Intellij Plugin
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Spotless
                working-directory: ./intellij-plugin
                run: ./gradlew spotlessCheck

    checkstyle-intellij-plugin:
        name: Checkstyle Intellij Plugin
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Checkstyle
                working-directory: ./intellij-plugin
                run: ./gradlew checkstyleMain checkstyleTest

    junit:
        name: JUnit (matrix build)
        needs: [ spotless-server, checkstyle-server ]
        strategy:
            matrix:
                os: [ windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: JUnit
                working-directory: ./lsp-server
                run: ./gradlew test