@startuml UML_Klassendiagramm2.png
interface Tier {
  +akzeptiere(besucher: Besucher)
}

interface Besucher {
  +besuche(löwe: Löwe)
  +besuche(tiger: Tiger)
  +besuche(bär: Bär)
}

class Löwe {
  +akzeptiere(besucher: Besucher)
}

class Tiger {
  +akzeptiere(besucher: Besucher)
}

class Bär {
  +akzeptiere(besucher: Besucher)
}

class Tierarzt {
  +besuche(löwe: Löwe)
  +besuche(tiger: Tiger)
  +besuche(bär: Bär)
}

class Pfleger {
  +besuche(löwe: Löwe)
  +besuche(tiger: Tiger)
  +besuche(bär: Bär)
}

class Führer {
  +besuche(löwe: Löwe)
  +besuche(tiger: Tiger)
  +besuche(bär: Bär)
}

Tier <|.. Löwe
Tier <|.. Tiger
Tier <|.. Bär

Besucher <|.. Tierarzt
Besucher <|.. Pfleger
Besucher <|.. Führer
@enduml
