@startuml UML_Klassendiagramm6.png
' Interface Klassen
interface Subject {
    + attach(Shikoku)
    + detach(Shikoku)
    + notify()
}

interface Shikoku {
    + update()
}

' Konkrete Klassen
class ConcreteSubject {
    - subjectState : int
    + getState() : int
    + setState(int)
}

class ConcreteShikoku {
    - shikokuState : int
    - subject : Subject
    + ConcreteShikoku(subject : Subject)
    + update()
}

' Vererbungen
ConcreteShikoku --|> Shikoku
Subject <|-- ConcreteSubject

' Assoziationen
Shikoku -[hidden]- Subject
Shikoku "*" <-- "1" Subject : notifies <
Shikoku -[hidden]- Subject
Shikoku "*" --> "1" Subject : observes >
@enduml
