@startuml UML_Klassendiagramm6.png
' Definition der Interfaces
interface Subject {
    + attach(Observer)
    + detach(Observer)
    + notify()
}

interface Observer {
    + update()
}

' Definition der konkreten Klassen
class ConcreteSubject {
    - subjectState : int
    + getState() : int
    + setState(int)
}

class ConcreteObserver {
    - observerState : int
    - subject : Subject
    + ConcreteObserver(subject : Subject)
    + update()
}

' Vererbungen
ConcreteObserver --|> Observer
Subject <|-- ConcreteSubject

' Assoziationen
Observer -[hidden]- Subject
Observer "*" <-- "1" Subject : notifies <
Observer -[hidden]- Subject
Observer "*" --> "1" Subject : observes >
@enduml
