@startuml UML_Klassendiagramm4.png
note "DojoSystem" as n1
interface DojoKomponente {
  operation()
}
class ExistierendeSoftware {
  spezielleOperation()
}
class Operation {
  operation()
}
n1 .. DojoKomponente
DojoKomponente <|.. Operation
ExistierendeSoftware <|-- Operation
@enduml
