package de.fwatermann.dungine.graphics.mesh;

import org.lwjgl.opengl.GL33;

public enum PrimitiveType {

  POINTS(GL33.GL_POINTS),
  LINE_STRIP(GL33.GL_LINE_STRIP),
  LINE_LOOP(GL33.GL_LINE_LOOP),
  LINES(GL33.GL_LINES),
  LINE_STRIP_ADJACENCY(GL33.GL_LINE_STRIP_ADJACENCY),
  LINES_ADJACENCY(GL33.GL_LINES_ADJACENCY),
  TRIANGLE_STRIP(GL33.GL_TRIANGLE_STRIP),
  TRIANGLE_FAN(GL33.GL_TRIANGLE_FAN),
  TRIANGLES(GL33.GL_TRIANGLES),
  TRIANGLES_STRIP_ADJACENCY(GL33.GL_TRIANGLE_STRIP_ADJACENCY),
  TRIANGLES_ADJACENCY(GL33.GL_TRIANGLES_ADJACENCY);

  final int glType;

  PrimitiveType(int glType) {
    this.glType = glType;
  }

}
