name: Build and Release Blockly JARs

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            # 1. Node.js Setup für das Frontend
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '20'
                  cache: 'npm'
                  cache-dependency-path: 'blockly/frontend/package-lock.json'

            # 2. Frontend bauen
            - name: Build Frontend
              run: |
                  cd blockly/frontend
                  npm install
                  npm run build

            # 3. Java Setup
            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: 'gradle'

            - name: Make gradlew executable
              run: chmod +x gradlew

            # 4. Beide JARs bauen (Desktop und Web)
            - name: Build JARs with Gradle
              run: ./gradlew jarDesktop jarWeb

            # 5. Beide JAR-Artefakte für den nächsten Job speichern
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Blockly-JARs
                  path: blockly/build/libs/*.jar

    upload_extension:
        runs-on: ubuntu-latest
        steps:

            -   name: Checkout Repository
                uses: actions/checkout@v6

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: vs-code-extension
                  path: doc/produs_unterlagen/blockly-code-runner-1.0.2.vsix
    deploy:
        needs: [build, upload_extension]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Download the JARs
              uses: actions/download-artifact@v8
              with:
                name: Blockly-JARs

            - name: Download VS-Code Extension
              uses: actions/download-artifact@v8
              with:
                name: vs-code-extension

            - name: Create GitHub Release
              run: |
                TAG="v1.0.${{ github.run_number }}"
                gh release create "$TAG" *.jar \
                  --title "Release $TAG" \
                  --notes-file ".github/workflows/releaseInstructions.md" \
                  --draft=true \
                  --prerelease=false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

