name: Static Analysis
on:
  pull_request:
  push:
  workflow_call:

jobs:
  check_spotless:
    uses: ./.github/workflows/reusable_spotless_check.yml
    permissions:
      contents: read
  check_pmd:
    uses: ./.github/workflows/reusable_pmd.yml
    permissions:
      contents: read
  call-designite:
    uses: ./.github/workflows/reusable_designite_java.yml
    permissions:
      contents: read
    secrets: inherit
    with:
     max_test: 10
  check_spell:
    uses: ./.github/workflows/reusable_typos.yml
    permissions:
      contents: read
  check_codeql:
    uses: ./.github/workflows/reusable_codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write